### ISSUE TITLE
Request for graphene SGX with cosmix

### ISSUE THREAD

**Issue by Bonjourz** [acsl-technion/cosmix#1]
Hi, you have mentioned the source codes of graphene SGX with cosmix will come soon. But I can't see them now... Could you please provide the source codes of graphene SGX with cosmix?

Thanks!

**Comment by shmeni** [comment]
We are working on publishing our port Graphene-SGX, we expect it to be made available in the next couple of days. 
Note, in case you wish to run cosmix with other mstores (not the SUVM mstore) and Graphene-SGX you can use the unmodified version.

**Comment by Bonjourz** [comment]
I got it. Thank you!

**Comment by shmeni** [comment]
We added our port of Graphene that exposes untrusted allocations directly to applications executing in Graphene-SGX: https://github.com/acsl-technion/graphene/tree/untrusted_alloc
Please let us know if you face any issues using it.
