### ISSUE TITLE
Run C++ program using Cosmix

### ISSUE THREAD

**Issue by donaldphw** [acsl-technion/cosmix#2]
Hi, I am trying the compile a C++ program with some external libraries using Cosmix(SVUM only), and I found that it is possible to use clang and LLVM to compile the scripts in native mode. However, I have faced some troubles in annotating the ptr in my scripts as the malloc is written in the external library. 

So, my question is that does Cosmix (SUVM mode) currently support compiling C++ program? If yes, may you give me some suggestion on annotating the malloc function in external libraries? Thanks.

**Comment by shmeni** [comment]
Hey, first, in our experience Cosmix on its own support C++ programs. However, the usage of instrumented pointers with libcxx is where things gets tricky if these instrumented pointers are passed to the library functions. The reason it shouldn't work correctly is obvious: it is incorrect to pass an instrumented pointer (e.g., with SUVM semantics) as a regular pointer (with native semantics). There are two options to go about it with Cosmix:
1. Instrument libcxx. That is, statically link it as you would any other library and the instrumentation with cosmix should be done automatically.
2. Create wrapper functions for the specific functions the application uses from libcxx. This is how Cosmix goes about libc for example, and the reason why it can operate with different SGX libOSes that uses different libc implementations.

Second, I'm not sure I fully understand the question. If you have a specific example that you use I can try and help more. For example, I'm not sure if your application uses libc's malloc or a custom implementation for memory allocation in the external libraries? If its the libc malloc, one way to go about it is to annotate it in the external libraries and statically link them before applying the cosmix pass. This would automatically instrument all the pointers in both the external libraries and the application.

**Comment by donaldphw** [comment]
Thank you for your reply and I can provide an example similar to what I am doing:

Let say I am trying to run the sample script of https://github.com/yixuan/MiniDNN under the SUVM mode in Cosmix. In that example, the script needs to call the function in eigen3 library, the function in its own header file. Also, as the malloc is called inside eigen3/Eigen/src/Core/utils/Memory.h, I cannot use the instrumented pointer directly. May you give me some suggestion to compile and run the script? Thanks.

**Comment by shmeni** [comment]
If I got the example correctly, you want to instrument pointers returned by the allocation at eigen3/Eigen/src/Core/utils/Memory.h:159, which is std:malloc.
To that end simply annotate that code as follows:
-    result = std::malloc(size);
+   result = __cosmix_suvm_annotation(std::malloc(size));
and also add the following line to Memory.h file (this is a known workaround to support annotations we have in Cosmix which we plan to fix soon with a more straightforward solution)
+ extern "C" void* __cosmix_suvm_annotation(void* ptr);

Then to compile with cosmix you can use the following set of commands (make sure you use the correct relative paths to your machine):
        $(LLVM_BIN)/clang++ -g -O2 -I$(MiniDNN_include_path) -I../$(eigen_path) -emit-llvm -c example.cpp -o test.bc
        $(LLVM_BIN)/llvm-link test.bc ../../runtime/cosmix_runtime.bc ../../mstores/common/common.bc ../../mstores/suvm/suvm_runtime.bc -o test_wrappers.bc
        $(LLVM_BIN)/opt < test_wrappers.bc -gvn -gvn-hoist -gvn-sink -loop-simplify -licm > test_loop_simplify.bc
        $(LLVM_BIN)/opt -load ../../pass/cosmix.so < test_loop_simplify.bc -cosmix -replace_all_allocators=false -code_analysis=false -config_file=$(current_dir)/suvm.json > test_inst.bc
        $(LLVM_BIN)/opt -O3 < test_inst.bc > test_opt.bc
        $(LLVM_BIN)/llc -relocation-model=pic -filetype=obj test_opt.bc -o test.o
        g++ test.o -o suvm -L../../libs -lsgx_tcrypto

**Comment by donaldphw** [comment]
Thanks for your reply and I just successfully compiled the script. However, when I try running the built script, it gives the following error message:

ASSERTION FAILED: cond = (page_offset + ptr_size) <= mstore_get_mpage_size(), file = cosmix_runtime.cpp, line = 682, 0 = 0
Aborted (core dumped)

May you give me some suggestion to fix it? Thanks for your help.

**Comment by shmeni** [comment]
This type of error usually means there is a cross page access, while rare we have no choice other than to read/write from multiple pages in that case, which may hurt the perf so its not enabled by default.
You can fix this by passing the following flag to cosmix: cross_page_cached_mstores_enabled=true
This changes the compilation command into something as follows:
$(LLVM_BIN)/opt -load ../../pass/cosmix.so < test_loop_simplify.bc -cosmix -replace_all_allocators=false -code_analysis=false -cross_page_cached_mstores_enabled=true -config_file=$(current_dir)/suvm.json > test_inst.bc

**Comment by Lucieno** [comment]
I'm curious that why cross-page access hurts the perf? 
Can it be avoided?

**Comment by shmeni** [comment]
For cached mstore like SUVM and when cross-page misaligned accesses occur, the cosmix runtime creates a temporary buffer and populates it by calling the mpf_handler_c for every page separately. For store access, the updates are written to both pages.
Since cosmix currently does not statically analyze pointers alignment it must always defer to runtime checks to figure out whether accesses are misaligned or not. These runtime checks may ultimately hurt the performance, and the the actual impact depends on the application and its memory accesses.

The way I see, to reduce this cost we can either employ static analysis that can prove accesses are always aligned with respect to the memory access size. 
However, I'm not sure how its possible to completely avoid this cost and I'm open to suggestions/ideas.
