### ISSUE TITLE
How to deploy cosmix for native SGX program

### ISSUE THREAD

**Issue by Lucieno** [acsl-technion/cosmix#3]
I'm trying to deploy cosmix for a project using the native SGX architecture,
where the code for the enclave and the untrusted zone is clearly separated.

My way is modifying my code for the enclave and Makefile according to [mem_access_benchmark](https://github.com/acsl-technion/cosmix/tree/master/samples/mem_access_benchmark)

However, I found that cosmix makes system calls so it is problematic when injecting mstore annotation in code for the enclaves and then compiling them with cosmix runtime .

Here is some snippet of the compilation error
```
Enclave/enclave_main.o: In function `__cosmix_debug':
llvm-link:(.text+0x787c): undefined reference to `stderr'
llvm-link:(.text+0x7887): undefined reference to `fputs'
Enclave/enclave_main.o: In function `__cosmix_allocate_buffer':
llvm-link:(.text+0x7959): undefined reference to `open'
llvm-link:(.text+0x7975): undefined reference to `mmap'
llvm-link:(.text+0x797f): undefined reference to `close'
Enclave/enclave_main.o: In function `default_mstore_write':
llvm-link:(.text+0x7a4c): undefined reference to `write'
Enclave/enclave_main.o: In function `default_mstore_read':
llvm-link:(.text+0x7a97): undefined reference to `read'
llvm-link:(.text+0x7aaf): undefined reference to `read'
Enclave/enclave_main.o: In function `__cosmix_free':
llvm-link:(.text+0x8387): undefined reference to `__assert_fail'
Enclave/enclave_main.o: In function `__cosmix_realloc':
llvm-link:(.text+0x8509): undefined reference to `__assert_fail'
llvm-link:(.text+0x8528): undefined reference to `__assert_fail'
```

Some snippet of my Makfile
```
Enclave/%.o: Enclave/%.cpp
    $(LLVM_BIN)/llvm-link $@.bc $(COSMIX_ROOT)/runtime/cosmix_runtime.bc $(COSMIX_ROOT)/mstores/common/common.bc $(COSMIX_ROOT)/mstores/suvm/suvm_runtime.bc -o $@.wrappers.bc
    $(LLVM_BIN)/opt < $@.wrappers.bc -gvn -gvn-hoist -gvn-sink -loop-simplify -licm > $@.loop_simplify.bc
    $(LLVM_BIN)/opt -load $(COSMIX_ROOT)/pass/cosmix.so < $@.loop_simplify.bc -cosmix -replace_all_allocators=false -code_analysis_integers=false -config_file=suvm.json > $@.inst.bc
    $(LLVM_BIN)/opt -O3 < $@.inst.bc > $@.opt.bc
    $(LLVM_BIN)/llc -relocation-model=pic -filetype=obj $@.opt.bc -o $@
    @echo "CXX  <=  $<"

$(Enclave_Name): $(Enclave_Cpp_Objects)
    $(CXX) $^ -o $@ $(Enclave_Link_Flags)
    @echo "LINK =>  $@"
```

Would you mind to give us guidelines of how to integrate cosmix with native SGX code?

**Comment by shmeni** [comment]
I'm afraid its not entirely clear to me when you say native SGX code do you refer to Intel's SGX SDK (https://github.com/intel/linux-sgx). If so, cosmix runtime and mstores can be compiled with the flag "SDK_BUILD=-DSDK_BUILD" that should remove these dependencies.
Unfortunately, I believe I created a bunch of compilation issues in one of my latest changes before publishing the code here on github, Sorry! I will try and push a fix to this and a sample code how to use cosmix with the SGX SDK in the next couple of days.

If you asked about a different env other than the SGX SDK, let me know.

**Comment by shmeni** [comment]
I've added an SGX SDK sample code to the repo at: https://github.com/acsl-technion/cosmix/tree/master/sgxsdk_samples/SampleEnclave
When testing it make sure to compile cosmix to work with the SDK_BUILD flag

**Comment by Lucieno** [comment]
Thanks for your help. I can get rid of the `undefined reference` errors. 
But now I face some errors due to the LLVM:
```
 [RUNNING PASS: COSMIX]
 [INFO] Total number of allocation calls instrumented 0
 [INFO] Total number of memory access instructions: 6425; Instrumented memory instructions are : 0%
 [INFO] Total number of memory instructions accessed in loops: 0; #optimized: 0
 Operand is null
   %4 = tail call i32 (i8*, i32, ...) <null operand!>(i8* %3, i32 2)
 Operand is null
   %6 = tail call i32 <null operand!>(i32 %4)
 LLVM ERROR: Broken function found, compilation aborted!
 Makefile:274: recipe for target 'enclave_code.o' failed
```
Would you mind to give me some hints of how to deal with that?

**Comment by shmeni** [comment]
I'm afraid its hard for me to reason about the error from this log. Would it be possible for you to provide a small program and compilation flags you use that reproduce this error?

One thing I can see from the log is that cosmix didn't instrument any allocations, so essentially it shouldn't change the semantics of any memory accesses performed by the enclave. I'm assuming this wasn't your intention. With an example of the compilation flags used it should be possible to solve that as well

**Comment by Lucieno** [comment]
This error occurs even when I tried to compile `cosmix/sgxsdk_samples/SampleEnclave` (inside the Docker container)

```
root@b2a2cf9365d8:/home/user/dev/cosmix/sgxsdk_samples/SampleEnclave# make
make[1]: Entering directory '/home/user/dev/cosmix/sgxsdk_samples/SampleEnclave'
GEN  =>  App/Enclave_u.h
CC   <=  App/Enclave_u.c
CXX  <=  App/App.cpp
LINK =>  app
GEN  =>  Enclave/Enclave_t.h
cc -m64 -O2 -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wcast-qual -Wconversion -Wredundant-decls -Wjump-misses-init -Wstrict-prototypes -Wunsuffixed-float-constants -I/home/user/dev/sgxsdk/include -I/home/user/dev/sgxsdk/include/tlibc -I/home/user/dev/sgxsdk/include/libcxx -nostdinc -fvisibility=hidden -fpie -ffunction-sections -fdata-sections -fstack-protector-strong -c Enclave/Enclave_t.c -o Enclave/Enclave_t.o
CC   <=  Enclave/Enclave_t.c
#@g++ -m64 -O2 -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wcast-qual -Wconversion -Wredundant-decls -Wnon-virtual-dtor -std=c++11 -I/home/user/dev/sgxsdk/include -I/home/user/dev/sgxsdk/include/tlibc -I/home/user/dev/sgxsdk/include/libcxx -nostdinc -fvisibility=hidden -fpie -ffunction-sections -fdata-sections -fstack-protector-strong -nostdinc++ -c Enclave/Enclave.cpp -o Enclave/Enclave.o
/home/user/llvm/bin/clang++ -O3 -m64 -O2 -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wcast-qual -Wconversion -Wredundant-decls -Wnon-virtual-dtor -std=c++11 -I/home/user/dev/sgxsdk/include -I/home/user/dev/sgxsdk/include/tlibc -I/home/user/dev/sgxsdk/include/libcxx -nostdinc -fvisibility=hidden -fpie -ffunction-sections -fdata-sections -fstack-protector-strong -nostdinc++ -emit-llvm -c Enclave/Enclave.cpp -o test.bc
/home/user/llvm/bin/llvm-link test.bc  ../../runtime/cosmix_runtime.bc ../../mstores/common/common.bc ../../mstores/suvm/suvm_runtime.bc -o test_wrappers.bc
/home/user/llvm/bin/opt < test_wrappers.bc -gvn -gvn-hoist -gvn-sink -loop-simplify -licm > test_loop_simplify.bc
/home/user/llvm/bin/opt -load ../../pass/cosmix.so < test_loop_simplify.bc -cosmix -replace_all_allocators=false -startup_func=ecall_main -code_analysis_integers=false -config_file=/home/user/dev/cosmix/sgxsdk_samples/SampleEnclave/suvm.json > test_inst.bc
[RUNNING PASS: COSMIX]
[INFO] replacing alloc func: __cosmix_malloc_suvm
[DBG] Running pointer analysis in function: ecall_main for annotated var:   %1 = tail call i8* @__cosmix_malloc_suvm(i64 1073741824)
[INFO] Total number of allocation calls instrumented 1
[INFO] Total number of memory access instructions: 418; Instrumented memory instructions are : 18%
[INFO] Total number of memory instructions accessed in loops: 31; #optimized: 13
Operand is null
  %4 = tail call i32 (i8*, i32, ...) <null operand!>(i8* %3, i32 2)
Operand is null
  %6 = tail call i32 <null operand!>(i32 %4)
LLVM ERROR: Broken function found, compilation aborted!
Makefile:256: recipe for target 'Enclave/Enclave.o' failed
make[1]: *** [Enclave/Enclave.o] Error 1
make[1]: Leaving directory '/home/user/dev/cosmix/sgxsdk_samples/SampleEnclave' 
Makefile:185: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by shmeni** [comment]
This is strange as I don't encounter this error when I'm building the sample in the container on my machine (builds successfully inside the container).
Just to make sure, could you please verify that the clang version installed in your container is 6.0.0 and that you git-pull and got the latest version of cosmix inside the container?

**Comment by Lucieno** [comment]
Thank @shmeni for your response. I just checked the version of clang and cosmix inside the container:

CLANG and LLVM
```
root@59102c94ae55:/home/user/dev/cosmix# clang --version
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/user/llvm/bin
root@59102c94ae55:/home/user/dev/cosmix# llvm-config --version
6.0.0
```

coxmis
```
root@59102c94ae55:/home/user/dev/cosmix# git log
commit 112323905aa365ed8cf8396ccc3dc879e3ca5226
Author: Meni Orenbach <shmenio@gmail.com>
Date:   Thu Sep 19 11:25:48 2019 +0300

    revivew SGX SDK support with a sample using SUVM

commit ea6c48a861d23d0eaabf1f6c3ab2c2d7f31059e9
Author: Meni Orenbach <shmenio@gmail.com>
Date:   Wed Sep 18 14:49:39 2019 +0300

    fix SGX SDK compilation issues
...
```

**Comment by shmeni** [comment]
Thank you for sharing, these versions looks right. 
I would also like to ask whether you changed the application code (SampleEnclave), mstores, runtime or cosmix pass? 
I will try running the docker image on another machine I have later today and see if I can reproduce the error and provide a fix.

**Comment by Lucieno** [comment]
Thanks for your help in advance.
In my container, nothing in cosmix is changed. Also, the runtime is compiled by command: 
`make clean && make SDK_BUILD=-DSDK_BUILD`

**Comment by shmeni** [comment]
Thanks. Unfortunately, the container in the other machine works as well so I can't reproduce the error by myself. 
Could you please attach the 'test_loop_simplify.bc' file here as. From the log posted its the input to cosmix and seems like it would contain the IR that causes the error, which can provide another way to reproduce the error.

**Comment by Lucieno** [comment]
Here you go:
https://www.dropbox.com/s/gfcne1vf8w01h1s/test_loop_simplify.bc

**Comment by shmeni** [comment]
I believe I found the issue.
The mstores should be compiled with `make SDK_BUILD=-DSDK_BUILD` as is the runtime. Sorry if that was not clear from my previous comments.

Here's the full details that causes this issue:
The SUVM mstore (mstores/suvm/suvm_runtime.cpp) has a function named `allocate_untrusted_buffer` which defaults to compile with mmap as a means to allocate a buffer in untrusted memory. With the SGX SDK, however, the untrusted allocation is currently achieved via an ocall.

On the other hand, cosmix integration with libc is through wrappers. This allows us to avoid instrumenting libc, which allows us to support multiple SGX execution environments (hence the different options to allocate buffers in untrusted memory).

One bootstrapping issue is that some libc functions used by mstores would be replaced with wrapper functions, which would call these mstores in turn and potentially result in an infinite recursion. To overcome this we tell cosmix to use the real libc functions in mstores where we can prove that is the case using the __real_ prefix. 

In ths SGX SDK libc (tlibc) file I/O functions are not available. So when the SUVM mstore is not compiled as SDK_BUILD, cosmix would try to patch these calls to the unavailable libc ones, which would cause the broken function error.

I will push a fix with a better error detection and reporting for this later today.
