### ISSUE TITLE
The performance of Native and SUVM in mem_access_benchmark does not differ

### ISSUE THREAD

**Issue by SamuelGong** [acsl-technion/cosmix#8]
Hi I am testing CoSMIX-compiled binary via SCONE containers. The program I am testing are those from `samples/mem_access_benchmark`. In particular, I am interested in the comparison of the generated binary of `native` and `suvm`. The `Makefile` is thus truncated to

```Makefile
include ../../Defines.mk

current_dir = $(shell pwd)

all : suvm native

cosmix:
	make -C $(COSMIX_DIR)/pass -f Makefile SDK_BUILD="-DSCONE_BUILD" NO_COUNTERS="-DNO_COUNTERS" RELEASE_BUILD="-DRELEASE_BUILD" SUVM_MIN_PTR_SIZE="-DSUVM_MIN_PTR_SIZE=1" SUVM_MAX_PTR_SIZE="-DSUVM_MAX_PTR_SIZE=1073741824" ORAM_BITS="-DORAM_BITS=28";
	make -C $(COSMIX_DIR)/runtime -f Makefile SDK_BUILD="-DSCONE_BUILD" NO_COUNTERS="-DNO_COUNTERS" RELEASE_BUILD="-DRELEASE_BUILD" SUVM_MIN_PTR_SIZE="-DSUVM_MIN_PTR_SIZE=1" SUVM_MAX_PTR_SIZE="-DSUVM_MAX_PTR_SIZE=1073741824" ORAM_BITS="-DORAM_BITS=28";
	make -C $(COSMIX_DIR)/mstores -f Makefile SDK_BUILD="-DSCONE_BUILD" NO_COUNTERS="-DNO_COUNTERS" RELEASE_BUILD="-DRELEASE_BUILD" SUVM_MIN_PTR_SIZE="-DSUVM_MIN_PTR_SIZE=1" SUVM_MAX_PTR_SIZE="-DSUVM_MAX_PTR_SIZE=1073741824" ORAM_BITS="-DORAM_BITS=28";

native: test.c
	$(LLVM_BIN)/clang -O3 -emit-llvm -c test.c -o test.bc
	$(LLVM_BIN)/llc -relocation-model=pic -filetype=obj test.bc -o test.o

suvm: test.c cosmix
	$(LLVM_BIN)/clang -O3 -emit-llvm -c test.c "-DSUVM_TEST" -o test.bc
	$(LLVM_BIN)/llvm-link test.bc $(COSMIX_DIR)/runtime/cosmix_runtime.bc $(COSMIX_DIR)/mstores/common/common.bc $(COSMIX_DIR)/mstores/suvm/suvm_runtime.bc -o test_wrappers.bc
	$(LLVM_BIN)/opt < test_wrappers.bc -gvn -gvn-hoist -gvn-sink -loop-simplify -licm > test_loop_simplify.bc
	$(LLVM_BIN)/opt -load $(COSMIX_DIR)/pass/cosmix.so < test_loop_simplify.bc -cosmix -replace_all_allocators=false -code_analysis_integers=false -config_file=$(current_dir)/suvm.json > test_inst.bc
	$(LLVM_BIN)/opt -O3 < test_inst.bc > test_opt.bc
	$(LLVM_BIN)/llc -relocation-model=pic -filetype=obj test_opt.bc -o test.o

clean:
	make -C $(COSMIX_DIR)/pass -f Makefile clean
	make -C $(COSMIX_DIR)/runtime -f Makefile clean
	rm -rf *.bc *.o *.log *.bin suvm native
```

and I perform the final compilation according to the suggestion in #6. The compilation was successful, however, when giving inputs `200` (which corresponds to generating an array of over 200MB) to both generated executables inside SCONE with hardware mode (meaning that I was in a proper SGX environment), respectively, I did not observe significantly difference between their printed `throughput`s and `latency`s.

To be exact, below are the corresponding commands I ran inside a SCONE container in hardware mode:

```bash
$ export SCONE_HEAP=256M && cd /suvm && gcc test.o -o native && ./native 200
Ops: 1000000, Latency: 0.000017, Throughput: 59245.104271
$ export SCONE_HEAP=256M && cd /suvm && g++ test.o libsgx_tcrypto.a -o suvm && ./suvm 200
Ops: 1000000, Latency: 0.000017, Throughput: 59136.169868
```

As one can see, my `native` even outperformed `suvm`.

Isn't `suvm` expected to perform much better when there is a great potential of **paging**, compared to `native`? Did I miss anything, again? Have you ever met any similar issue when testing your `samples/mem_access_benchmark`? (As I can see SCONE-related stuffs in the `Makefile`, I guess that you had already tried testing this benchmark with SCONE before.)

**Comment by shmeni** [comment]
The settings that you've pasted don't seem right. You compile both the native and suvm executables from the **same** test.o file. This means both executables will be the same so observing similar performance would make sense.

**Comment by SamuelGong** [comment]
Thanks for your insight! Indeed, when delegating the final step of compilation of `native` and `suvm` to SCONE, I ignored to differentiate the intermediate result `test.o` that they used. As a result,  both of them were ultimately based on the `test.o` of `native`.

With that lesson born in mind, I changed the above Makefile into

```Makefile
include ../Defines.mk

current_dir = $(shell pwd)

all : suvm native

cosmix:
	make -C $(COSMIX_DIR)/pass -f Makefile SDK_BUILD="-DSCONE_BUILD" NO_COUNTERS="-DNO_COUNTERS" RELEASE_BUILD="-DRELEASE_BUILD" SUVM_MIN_PTR_SIZE="-DSUVM_MIN_PTR_SIZE=1" SUVM_MAX_PTR_SIZE="-DSUVM_MAX_PTR_SIZE=1073741824" ORAM_BITS="-DORAM_BITS=28";
	make -C $(COSMIX_DIR)/runtime -f Makefile SDK_BUILD="-DSCONE_BUILD" NO_COUNTERS="-DNO_COUNTERS" RELEASE_BUILD="-DRELEASE_BUILD" SUVM_MIN_PTR_SIZE="-DSUVM_MIN_PTR_SIZE=1" SUVM_MAX_PTR_SIZE="-DSUVM_MAX_PTR_SIZE=1073741824" ORAM_BITS="-DORAM_BITS=28";
	make -C $(COSMIX_DIR)/mstores -f Makefile SDK_BUILD="-DSCONE_BUILD" NO_COUNTERS="-DNO_COUNTERS" RELEASE_BUILD="-DRELEASE_BUILD" SUVM_MIN_PTR_SIZE="-DSUVM_MIN_PTR_SIZE=1" SUVM_MAX_PTR_SIZE="-DSUVM_MAX_PTR_SIZE=1073741824" ORAM_BITS="-DORAM_BITS=28";

native: test.c
	$(LLVM_BIN)/clang -O3 -emit-llvm -c test.c -o test.bc
	$(LLVM_BIN)/llc -relocation-model=pic -filetype=obj test.bc -o test_native.o

suvm: test.c cosmix
	$(LLVM_BIN)/clang -O3 -emit-llvm -c test.c "-DSUVM_TEST" -o test.bc
	$(LLVM_BIN)/llvm-link test.bc $(COSMIX_DIR)/runtime/cosmix_runtime.bc $(COSMIX_DIR)/mstores/common/common.bc $(COSMIX_DIR)/mstores/suvm/suvm_runtime.bc -o test_wrappers.bc
	$(LLVM_BIN)/opt < test_wrappers.bc -gvn -gvn-hoist -gvn-sink -loop-simplify -licm > test_loop_simplify.bc
	$(LLVM_BIN)/opt -load $(COSMIX_DIR)/pass/cosmix.so < test_loop_simplify.bc -cosmix -replace_all_allocators=false -code_analysis_integers=false -config_file=$(current_dir)/suvm.json > test_inst.bc
	$(LLVM_BIN)/opt -O3 < test_inst.bc > test_opt.bc
	$(LLVM_BIN)/llc -relocation-model=pic -filetype=obj test_opt.bc -o test_suvm.o

clean:
	make -C $(COSMIX_DIR)/pass -f Makefile clean
	make -C $(COSMIX_DIR)/runtime -f Makefile clean
	rm -rf *.bc *.o *.log *.bin suvm native
```

and the commands I ran became

```bash
$ export SCONE_HEAP=256M && cd /suvm && gcc test_native.o -o native && ./native 64
Ops: 1000000, Latency: 0.000007, Throughput: 147773.507367
$ export SCONE_HEAP=256M && cd /suvm && g++ test_suvm.o libsgx_tcrypto.a -o suvm && ./suvm 64
ASSERTION FAILED: cond = bs_ptr != MAP_FAILED, file = suvm_runtime.cpp, line = 121, 0 = 0
```

As one can see, this time the two generated binary did differ. However, it seemed that something was broken with `suvm`. Do anyone know why did I receive such an **assertion failure**? By the way, the `suvm.json` I used in compilation was unmodified, i.e., exactly same as the one in the repo:

```json
{
  "mstores": [
    {
      "name" : "suvm",
      "annotation_symbol": "suvm",
      "function_annotation_name": "__cosmix_suvm_annotation",
      "type": "cached",
      "storage": "mem",
      "TLB" : true,
      "EvictThread" : true,
      "BoundsAllocation": false,
      "LowerBound": 10,
      "UpperBound": 100000000
    }
  ]
}
```

Does the configuration in this file matter? Or does the setting of some important environment variables in SCONE matter? Looking forward to your help, again!

**Comment by shmeni** [comment]
The assertion states that the way suvm allocates untrusted memory in SCONE failed. Its hard to say what causes this error without more information of what changed in the version of SCONE youre using unfortunately.

**Comment by SamuelGong** [comment]
Alright, let me try to confirm with SCONE team via email. I will come back if obtaining anything worth sharing. By the way, if you are aware of the reason later, please notify me as I am still looking forward to the solution!

Thanks for your prompt response.

**Comment by SamuelGong** [comment]
Hi CoSMIX Team,

As a response from SCONE's team, they say that the code used to work to create memory on the outside. However, they have disabled this feature to avoid security issues. And they suggest allocating some memory on the inside to see if the software paging works.

I am not sure what they mean. Does it make sense to you? If yes, how to change the code?

**Comment by shmeni** [comment]
SUVM as its currently implemented uses untrusted memory as the backing store. If it's no longer possible to allocate untrusted memory in SCONE then we can't support SUVM there easily. I'd suggest trying with an alternative runtime like Graphene-SGX or SGX-SDK for which we provide prototypes that include untrusted memory allocation.

**Comment by silbmarks** [comment]
I would saymore than that.. If there's no untrusted memory allocated for
SUVM then I don't really see why exactly one would ever want to use SUVM?

**Comment by SamuelGong** [comment]
> SUVM as its currently implemented uses untrusted memory as the backing store. If it's no longer possible to allocate untrusted memory in SCONE then we can't support SUVM there easily. I'd suggest trying with an alternative runtime like Graphene-SGX or SGX-SDK for which we provide prototypes that include untrusted memory allocation.

Hi CoSMIX Team,

I have tried out a legacy version of SCONE (`scone3`) and it does support allocating untrusted memory. Now the performance of both `native` and `suvm` are available and do differ as follows:

```bash
$ export SCONE_HEAP=256M && cd /suvm && g++ test_native.o -o native && g++ test_suvm.o libsgx_tcrypto.a -o suvm

$ ./native 64
Ops: 1000000, Latency: 0.000006, Throughput: 175400.491688
$ ./suvm 64
Ops: 1000000, Latency: 0.000009, Throughput: 106548.583991

$ ./native 128
Ops: 1000000, Latency: 0.000006, Throughput: 174964.444627
$ ./suvm 128
Ops: 1000000, Latency: 0.000012, Throughput: 82293.461855

$ ./native 192
Ops: 1000000, Latency: 0.000006, Throughput: 175893.324678
$ ./suvm 192
Ops: 1000000, Latency: 0.000013, Throughput: 77818.405653

$ ./native 256
Assertion failed: x (test.c: int main(int, char **): 68)
[SCONE|FATAL] ./tools/starter-exec.c:97:exit_signal(): Aborted
$ ./suvm 256
Ops: 1000000, Latency: 0.000013, Throughput: 75072.961349
```

Now I cannot see **why `suvm` works worse than `native`**. Does these results make sense to you? What should be the expected results?

**Comment by SamuelGong** [comment]
> SUVM as its currently implemented uses untrusted memory as the backing store. If it's no longer possible to allocate untrusted memory in SCONE then we can't support SUVM there easily. I'd suggest trying with an alternative runtime like Graphene-SGX or SGX-SDK for which we provide prototypes that include untrusted memory allocation.

Hi CoSMIX Team,

I have tried out a legacy version of SCONE (`scone3`) and it does support allocating untrusted memory. Now the performance of both `native` and `suvm` are available and do differ as follows:

```bash
$ export SCONE_HEAP=256M && cd /suvm && g++ test_native.o -o native && g++ test_suvm.o libsgx_tcrypto.a -o suvm

$ ./native 64
Ops: 1000000, Latency: 0.000006, Throughput: 160246.191403
$ ./suvm 64
Ops: 1000000, Latency: 0.000010, Throughput: 96282.644744

$ ./native 96
Ops: 1000000, Latency: 0.000006, Throughput: 160800.993383
$ ./suvm 96
Ops: 1000000, Latency: 0.000012, Throughput: 81790.771849

$ ./native 128
Ops: 1000000, Latency: 0.000010, Throughput: 100332.976021
$ ./suvm 128
Ops: 1000000, Latency: 0.000013, Throughput: 75133.879074

$ ./native 160
Ops: 1000000, Latency: 0.000015, Throughput: 68177.692892
$ ./suvm 160
Ops: 1000000, Latency: 0.000014, Throughput: 72148.315703

$ ./native 192
Ops: 1000000, Latency: 0.000018, Throughput: 55491.282497
$ ./suvm 192
Ops: 1000000, Latency: 0.000015, Throughput: 68815.543044

$ ./native 224
Ops: 1000000, Latency: 0.000020, Throughput: 49316.223647
$ ./suvm 224
Ops: 1000000, Latency: 0.000014, Throughput: 69141.134584

$ ./native 256
Assertion failed: x (test.c: int main(int, char **): 68)
[SCONE|FATAL] ./tools/starter-exec.c:97:exit_signal(): Aborted
$ ./suvm 256
Ops: 1000000, Latency: 0.000015, Throughput: 66468.870008
```

As one can see, I set the heap that SCONE can use in SGX mode to be `256M`. As the input (which is size of part of the allocated memory in `test.c`) grows larger from `64`, `native` first outperforms `suvm` in terms of running time (as well as throughput). Then the **crossover point** occurs at about `160`, since which `suvm` starts to surpass `native`. Finally, when input mounts to 256, the actual space needed to allocate is larger than the heap size allowed so `native` just throws exception, while `suvm` can still work as we are using user-level paging and the pages are from untrusted memory.

I think all these make sense to me and lift up to my expectations. I thus share them with anybody interested in this issue. Of course, it is time to close this issue.

Thanks again to CoSMIX Team for helpful debugging and insightful discussion! Really appreciate it.

**Comment by silbmarks** [comment]
Thanks for sharing!
