### ISSUE TITLE
Failed to do fread() over SUVM allocated memory (inside SCONE)

### ISSUE THREAD

**Issue by SamuelGong** [acsl-technion/cosmix#9]
Hi CoSMIX Team,

*First of all, I am using CoSMIX on top of SCONE (to be exact, the image I used for SCONE is `crosscompiler/alphine-scone3`, since latest scone does not support untrusted memory allocation.*

It seems that the memory allocated by SUVM can support direct assignment, however, cannot be used to do `fread()`, that is, storing content fetched from a file. To be exact, this will cause a **segmentation fault** I provided a minimal example here:

### Source code

```c
#include <stdio.h>
#include <stdlib.h>

extern void* __cosmix_suvm_annotation(void* ptr);

int main(int argc, char** argv) {
#ifdef SUVM_TEST
	int *array = (int *)__cosmix_suvm_annotation(malloc(10000 * sizeof(int)));
#else
	int *array = (int *)malloc(10000 * sizeof(int));
#endif

	printf("We can allocate\n");
	fflush(stdout);

	for (int i = 0; i < 10000; i++) {
		array[i] = 0;
	}
	printf("We can directly assign\n");
	fflush(stdout);

	FILE * pFile;
	if((pFile = fopen("data.bin", "rb")) == NULL ){
		puts("Fail to open data.bin!");
		exit(1);
	}
	fread(array, sizeof(int), 10000, pFile);

	printf("We can also do fread\n");
	fflush(stdout);

	fclose(pFile);
	free(array);
	return 0;
}
```

### Program Output

For `native`,

```bash
We can allocate
We can directly assign
We can also do fread
```

For `suvm`,

```
We can allocate
We can directly assign
[SCONE|FATAL] ./tools/starter-exec.c:97:exit_signal(): Segmentation fault
```

Are you aware of this issue before? Why is `fread()` so special?

**Comment by SamuelGong** [comment]
Additional information: this problem does not exist if we don't use CoSMIX atop `scone3` according to my confirmation.

**Comment by shmeni** [comment]
When using external libraries (not compiled through CoSMIX) one must provide wrappers for the functions used. These wrappers allow CoSMIX to work with runtimes such as SCONE without recompiling them. The wrappers are located at: https://github.com/acsl-technion/cosmix/blob/master/runtime/cosmix_runtime.cpp
To the best of my knowledge, CoSMIX doesn't have a wrapper for the fread(...) function but it should be simple to add one, e.g., based on the read(...) function wrapper: https://github.com/acsl-technion/cosmix/blob/4e67f559a8f065b6367d83be7ee1f3e160437c73/runtime/cosmix_runtime.cpp#L1858

**Comment by SamuelGong** [comment]
OK, but I still don't understand why the problem does not occur for the `native` case, where CoSMIX still works with SCONE?

**Comment by shmeni** [comment]
If you consider `native` as compiling the application with CoSMIX but not annotating any memory allocation then nothing would be instrumented and it should be equivalent to not using CoSMIX.

**Comment by SamuelGong** [comment]
Alright, then this is my walk-around: instead of giving a `__cosmix_fread()`, I chose to directly utilize the existing `__cosmix_read()` by converting (sample code here)

```C++
    fread(ptr, size, count, stream);
```

to

```C++
#ifdef SUVM_TEST
    int fd = fileno(stream);
    __cosmix_read(fd, ptr, size * count);
#else
    fread(ptr, size, count, stream);
#endif
```

And this seems to work for me.

Before I close this issue, can I have your comments of doing that? To be exact,
* What would be the difference between doing so and newly defining your `__cosmix_fread()`?

Thanks a lot!

**Comment by shmeni** [comment]
The difference is rooted in which libc function will be invoked eventually: `read()` or `fread()`.

In general, the easier method to define a wrapper in CoSMIX is to transform the pointer arguments into native pointers if they are tagged by CoSMIX. To see if they are tagged by CoSMIX you can use the `IS_COSMIX_PTR` macro, allocate a new buffer and copy the data using `__cosmix_memcpy()` (again for an example on how it's done you can refer to `cosmix_read()`) 
For `size_t fread(void *ptr, size_t size, size_t nmemb, FILE *stream);` there are two such potential pointers: `void* ptr` and `FILE* stream` that needs to be checked and transformed if needed.

**Comment by SamuelGong** [comment]
Thanks for your instructions! I am glad to close this issue now.
